services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duofin_app
    restart: always
    environment:
      - APP_ENV=production
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - web_network

networks:
  web_network:
    external: true