services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: duofin_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env
    networks:
      - web_network

networks:
  web_network:
    external: true